Document: paperbark
Title: Debian paperbark Manual
Author: <insert document author here>
Abstract: This manual describes what paperbark is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/paperbark/paperbark.sgml.gz

Format: postscript
Files: /usr/share/doc/paperbark/paperbark.ps.gz

Format: text
Files: /usr/share/doc/paperbark/paperbark.text.gz

Format: HTML
Index: /usr/share/doc/paperbark/html/index.html
Files: /usr/share/doc/paperbark/html/*.html
