#!/bin/bash
commands['list']='list staging filesystems'
command_alias['ls']='list'


list_help() {
    echo """usage:
    $pb_exec list|ls [OPTIONS]

where OPTIONS are
    -h | --help
        this help message
    -H
        script mode, do not show column header
"""

    exit 0
}

cmd_list_prepare() {
    pb_prepare_repository

    while [[ 0 != $# ]]; do
        case "$1" in
            -h | --help)
                list_help
                ;;
            -H)
                list_script_mode=yes
                ;;
        esac
        shift
    done
}

cmd_list_exec() {
    _list_exec() {
        printf "%37s    %s\n" "$1" "${_zfs_stag_deps["$1"]##*@}"
    }

    if [[ -z "$list_script_mode" ]]; then
        printf "%37s    %s\n" STAGING-FS FROM
    fi
    staging_enum _list_exec
}
