#!/bin/bash
commands['search']='handle search request from client side'

cmd_search_prepare() {
    return
}

cmd_search_exec() {
    read query

    local -a snaps
    for snap in "${_zfs_snaps[@]}"; do
        if snapshot_is_marked_destroyed "$snap"; then
            continue
        fi

        snap="${snap##*@}"
        if [[ "${snap%:*}" = $query ]]; then
            snaps+=($snap)
        fi
    done

    echo ${snaps[@]}
}
