#!/bin/bash
commands['pull']='handler pull request from client side pb'

cmd_pull_prepare() {
    pull_snapshot=$1
}

cmd_pull_exec() {
    if ! snapshot_id_normalize "$pull_snapshot" pull_snapshot; then
        echo snapshot not found: $pull_snapshot >&2
        return 1
    fi

    snapshot_series_get "$pull_snapshot" snapshots

    snapshot_series_send_and_receive_diff snapshots "${snapshots[@]}"

    snapshot_send_all true "${snapshots[@]}"
}
